import Head from 'next/head'
import Image from 'next/image'

import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>JLG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>
            JLG UNIVERSITY
          </p>
          <div>
            <h1>Home page</h1>
          </div>
        </div>

        <div>
          <Image
            src="https://cpcontents.adobe.com/public/account/119202/thumbnails/learningplans/114514/2023-08-01%2012:42:13.135jlgu_classroom_MG_7771_8be1e45514944e138390e86540c7ab76.png"
            alt="Next.js Logo"
            width={290}
            height={180}
            priority
            style={{
              // objectFit: 'cover',
              maxWidth: '100%', // Ensure the image doesn't exceed its container's width
              maxHeight: '180px',
              height: 'auto',
            }}
          /><br />

        </div>
        <Link href={'/id'} style={{ padding: '10px 20px', border: '1px solid orange' }}>View details</Link>
      </main>
    </>
  )
}
