import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GoogleTagManager, sendGTMEvent, GoogleAnalytics } from '@next/third-parties/google'
import { useRouter } from 'next/router'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const router = useRouter()
  const viewDetails = () => {
    sendGTMEvent({
      event: 'view_item',
      currency: "USD",
      value: 100,
      items: [
        {
          item_id: 1,
          item_name: "JLG",
          item_category: "Course",
          price: 100,
          quantity: 1
        }
      ]
    })
    router.push('/id')
  }
  return (
    <>
      <Head>
        <title>JLG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <GoogleTagManager gtmId="GTM-MK3PVXGP" />
        <GoogleAnalytics gaId="G-TQJT5VB0DP" />
        <div className={styles.description}>
          <p>
            JLG UNIVERSITY
          </p>
          <div>
            <h1>Testing..</h1>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            src="https://cpcontents.adobe.com/public/account/119202/thumbnails/learningplans/114514/2023-08-01%2012:42:13.135jlgu_classroom_MG_7771_8be1e45514944e138390e86540c7ab76.png"
            alt="Next.js Logo"
            width={290}
            height={180}
            priority
            style={{
              // objectFit: 'cover',
              maxWidth: '100%', // Ensure the image doesn't exceed its container's width
              maxHeight: '180px',
              height: 'auto',
            }}
          /><br />

        </div>
        <button onClick={viewDetails} style={{ padding: '10px 20px', border: '1px solid orange' }}>View details</button>
      </main>
    </>
  )
}
